# Generated by Django 5.2.8 on 2025-11-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='category name')),
                ('image', models.ImageField(upload_to='images', verbose_name='upload image')),
                ('descriptions', models.TextField(verbose_name='description')),
            ],
        ),
    ]
