# Generated by Django 5.2.8 on 2025-11-25 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='category name')),
                ('image', models.ImageField(upload_to='images', verbose_name='upload image')),
                ('descriptions', models.TextField(verbose_name='description')),
                ('price', models.FloatField(verbose_name='price')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
                ('created', models.DateTimeField(verbose_name='created')),
                ('updated', models.DateTimeField(verbose_name='updated')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category_model')),
            ],
        ),
    ]
