# Generated by Django 5.2.8 on 2025-11-27 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_model',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='shop.category_model'),
        ),
        migrations.AlterField(
            model_name='product_model',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='product_model',
            name='name',
            field=models.CharField(max_length=50, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product_model',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='updated'),
        ),
    ]
